#!/bin/bash

if [ $# == 0 ]; then
    echo "Must supply a project name as the first argument."
    exit 1 
fi
    
if [ -e $1 ]; then
    echo "Project '$1' already exists."
    exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_NAME=$1
DATE=`date`
HOST=`hostname`

README=${PROJECT_NAME}/README.md
GO=${PROJECT_NAME}/go
ANALYZE=${PROJECT_NAME}/scripts/analyze.pl
EMPTY_ANALYSIS=${PROJECT_NAME}/scripts/analysis_empty.pl

mkdir -p ${PROJECT_NAME}/{bin,data,lists,reports,results,resources,scratch,scripts,scripts/lib}

sed "s/<PROJECT_NAME>/${PROJECT_NAME}/g" ${SCRIPT_DIR}/README.template | sed "s/<DATE>/${DATE}/g" > ${README}

cp ${SCRIPT_DIR}/gitignore ${PROJECT_NAME}/.gitignore
cp ${SCRIPT_DIR}/analyze.pl ${ANALYZE}
cp ${SCRIPT_DIR}/analysis_empty.pl ${EMPTY_ANALYSIS}
cp ${SCRIPT_DIR}/*.pm ${PROJECT_NAME}/scripts/lib/
cp ${SCRIPT_DIR}/go ${GO}
chmod 755 ${GO}

(cd ${PROJECT_NAME} && git init)
(cd ${PROJECT_NAME} && git remote add kvg git@github.com:kvg/${PROJECT_NAME}.git)
(cd ${PROJECT_NAME} && git remote add lab git@github.com:mcveanlab/${PROJECT_NAME}.git)
(cd ${PROJECT_NAME} && git add go README.md .gitignore scripts/analyze.pl scripts/lib/*)
(cd ${PROJECT_NAME} && git commit -m "Initial commit" -a)
